apiVersion: v1
kind: Namespace
metadata:
  name: permission-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-namespaced-resources___operation
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-namespaced-resources___developer
rules:
  - apiGroups:
      - "*"
    resources:
      # - "bindings"
      - "configmaps"
      - "endpoints"
      # - "limitranges"
      - "persistentvolumeclaims"
      - "pods"
      - "pods/log"
      - "pods/portforward"
      - "podtemplates"
      - "replicationcontrollers"
      - "resourcequotas"
      - "secrets"
      # - "serviceaccounts"
      - "services"
      # - "controllerrevisions"
      # - "statefulsets"
      # - "localsubjectaccessreviews"
      # - "horizontalpodautoscalers"
      # - "cronjobs"
      # - "jobs"
      # - "leases"
      - "events"
      - "daemonsets"
      - "deployments"
      - "replicasets"
      - "ingresses"
      - "networkpolicies"
      - "poddisruptionbudgets"
      # - "rolebindings"
      # - "roles"
    verbs:
      - "*"
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: template-namespaced-resources___consultant
# rules:
#   - apiGroups:
#       - "*"
#     resources:
#       - "configmaps"
#       - "pods"
#     verbs:
#       - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-cluster-resources___read-only
rules:
  - apiGroups:
      - "*"
    resources:
      - "componentstatuses"
      - "namespaces"
      - "nodes"
      - "persistentvolumes"
      - "mutatingwebhookconfigurations"
      - "validatingwebhookconfigurations"
      - "customresourcedefinitions"
      - "apiservices"
      - "tokenreviews"
      - "selfsubjectaccessreviews"
      - "selfsubjectrulesreviews"
      - "subjectaccessreviews"
      - "certificatesigningrequests"
      - "runtimeclasses"
      - "podsecuritypolicies"
      - "clusterrolebindings"
      - "clusterroles"
      - "priorityclasses"
      - "csidrivers"
      - "csinodes"
      - "storageclasses"
      - "volumeattachment"
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: template-cluster-resources___admin
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
      # - "componentstatuses"
      # - "namespaces"
      # - "nodes"
      # - "persistentvolumes"
      # - "mutatingwebhookconfigurations"
      # - "validatingwebhookconfigurations"
      # - "customresourcedefinitions"
      # - "apiservices"
      # - "tokenreviews"
      # - "selfsubjectaccessreviews"
      # - "selfsubjectrulesreviews"
      # - "subjectaccessreviews"
      # - "certificatesigningrequests"
      # - "runtimeclasses"
      # - "podsecuritypolicies"
      # - "clusterrolebindings"
      # - "clusterroles"
      # - "priorityclasses"
      # - "csidrivers"
      # - "csinodes"
      # - "storageclasses"
      # - "volumeattachment"
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: permission-manager-service-account-rolebinding
  namespace: permission-manager
roleRef:
  kind: Role
  name: permission-manager-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: permission-manager-service-account
    namespace: permission-manager
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: permission-manager-service-account-rolebinding
roleRef:
  kind: ClusterRole
  name: permission-manager-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: permission-manager-service-account
    namespace: permission-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: permission-manager-service-account
  namespace: permission-manager
imagePullSecrets:
  - name: sighup-gitlab-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permission-manager-cluster-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "permissionmanagerusers"
      - "clusterrolebindings"
      - "clusterroles"
      - "rolebindings"
      - "roles"
      - "certificatesigningrequests"
      - "certificatesigningrequests/approval"
    verbs:
      - "*"

  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs: ["get", "list"]
